name: Mutation Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      AppVeyorBuild: true
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup .NET 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET 2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
        
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
      
    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker
    
    - name: Run Stryker FlatSharp
      working-directory: src/FlatSharp
      run: dotnet-stryker
      
    - name: Run Stryker FlatSharp.Runtime
      working-directory: src/FlatSharp.Runtime
      run: dotnet-stryker
      
    - name: Run Stryker FlatSharp.Compiler
      working-directory: src/FlatSharp.Compiler
      run: dotnet-stryker
